name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.0.4
  animate_do: ^3.1.2
  curved_navigation_bar: ^1.0.6
  flutter_form_builder: ^9.3.0
  form_builder_validators:
  uuid: ^4.4.0
  simple_barcode_scanner: ^0.1.1
  pdf: ^3.11.0
  printing: ^5.13.1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl:
  arabic_font: ^0.0.9
  syncfusion_flutter_charts: ^26.1.42
  connectivity_checker: ^1.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.1
  flutter_local_notifications: ^17.2.2
  barcode: ^2.2.8
  cached_network_image: ^3.4.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: "assets/images/logo.png"
  color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1.otf

    - family: Amiri-Regular
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    
    - family: Amiri-Bold
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf

  assets:
    - assets/images/
    - assets/sounds/
